(()=>{'use strict';
const SUPA='https://ptblnpiroqftcvlsrhac.supabase.co',KEY='sb_publishable_SqXIeGN-clcZ4gjmpLdSww_4DLfyy24';
if(!window.supabase)return;
const sb=window.supabase.createClient(SUPA,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const state={overview:null,last:{idx:null,sup:null,push:null}};
const css=`
.kcx-ledrow{display:grid;grid-template-columns:auto 11px;gap:2px 6px;align-items:center;cursor:pointer;min-width:58px}.kcx-traffic{width:9px;height:9px;border-radius:50%;background:#8a7a67;opacity:.35;transition:.08s}.kcx-traffic.flash{background:#f2bd22;opacity:1;box-shadow:0 0 9px #f2bd22}.kcx-dot{display:inline-block;width:12px;height:12px;border-radius:50%;vertical-align:-1px;margin-right:7px;background:#999;box-shadow:0 0 0 1px rgba(0,0,0,.08)}.kcx-dot.green{background:#24834f;box-shadow:0 0 8px #24834f}.kcx-dot.yellow{background:#d69715;box-shadow:0 0 8px #d69715}.kcx-dot.red{background:#bd2f2f;box-shadow:0 0 8px #bd2f2f}.kcx-dot.blue{background:#2878c7;box-shadow:0 0 8px #2878c7}.kcx-dot.gray{background:#999}.kcx-table{width:100%;border-collapse:collapse}.kcx-table th,.kcx-table td{padding:11px 9px;border-bottom:1px solid #e7dfd6;text-align:left;vertical-align:top}.kcx-table th{font-size:12px;text-transform:uppercase;letter-spacing:.04em;color:#746b64}.kcx-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:14px}.kcx-provider{border:1px solid #ded6cd;border-radius:14px;padding:14px;background:#fff}.kcx-provider h3{margin:0 0 8px}.kcx-route{display:grid;grid-template-columns:1fr auto;gap:6px;border-top:1px solid #eee5dc;padding:8px 0}.kcx-modal{border:1px solid #ded6cd;border-radius:18px;width:min(760px,95vw);padding:20px;box-shadow:0 18px 55px rgba(30,20,15,.25)}.kcx-modal::backdrop{background:rgba(20,15,12,.45)}.kcx-gauges{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:16px 0}.kcx-gauge{display:grid;place-items:center}.kcx-dial{--p:0;display:grid;place-items:center;width:150px;height:150px;border-radius:50%;background:conic-gradient(#24834f calc(var(--p)*1%),#ece5de 0);position:relative}.kcx-dial:before{content:'';position:absolute;inset:13px;border-radius:50%;background:white}.kcx-dial b,.kcx-dial small{position:relative;z-index:1}.kcx-dial b{font-size:26px}.kcx-dial small{display:block;text-align:center;color:#6d6966}.kcx-statusbar{display:flex;gap:12px;flex-wrap:wrap;align-items:center;margin-bottom:12px}.kcx-pill{border-radius:999px;padding:5px 9px;font-size:12px;font-weight:800;background:#eee}.kcx-pill.ok{background:#e7f4eb;color:#237447}.kcx-pill.warn{background:#fff2dc;color:#9a6309}.kcx-pill.bad{background:#fff0ef;color:#922e2e}.kcx-pill.info{background:#eaf2fb;color:#24639a}.kcx-small{font-size:12px;color:#6d6966}.kcx-action{border:1px solid #ded6cd;background:#fff;border-radius:10px;padding:8px 11px;font-weight:700;cursor:pointer}.kcx-action.primary{background:#741521;color:white;border-color:#741521}.kcx-action:disabled{opacity:.5}.kcx-note{padding:10px 12px;border-radius:10px;background:#f3eee7;margin-top:10px}.kcx-error{background:#fff0ef;color:#922e2e}.kcx-secret{font-family:Consolas,monospace;font-size:11px;background:#f4f1ed;padding:2px 5px;border-radius:5px}@media(max-width:700px){.kcx-gauges{grid-template-columns:1fr}.kcx-table{font-size:13px}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function flash(kind){const el=document.getElementById('kcx-'+kind+'-traffic');if(!el)return;el.classList.add('flash');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('flash'),180);}
const origFetch=window.fetch.bind(window);window.fetch=async(...args)=>{const u=String(args[0]?.url||args[0]||'');if(u.includes('supabase.co'))flash(u.includes('push')?'push':'sup');return origFetch(...args)};
try{const origOpen=indexedDB.open.bind(indexedDB);indexedDB.open=(...a)=>{flash('idx');return origOpen(...a)}}catch{}
function enhanceLEDs(){document.querySelectorAll('.dbs .db').forEach((box,i)=>{if(box.dataset.kcx)return;box.dataset.kcx='1';const kind=['idx','sup','push'][i]||'sup';box.classList.add('kcx-ledrow');box.insertAdjacentHTML('beforeend',`<span class="kcx-small">Traffic</span><i id="kcx-${kind}-traffic" class="kcx-traffic" title="Echter Datenverkehr"></i>`);box.title='Klicken für Info, Messwerte und Tests';box.addEventListener('click',()=>openDiag(kind));});}
function ensureModal(){let d=document.getElementById('kcxDiag');if(d)return d;d=document.createElement('dialog');d.id='kcxDiag';d.className='kcx-modal';d.innerHTML='<div id="kcxDiagBody"></div><div style="display:flex;justify-content:flex-end;margin-top:14px"><button class="kcx-action" id="kcxClose">Schließen</button></div>';document.body.appendChild(d);d.querySelector('#kcxClose').onclick=()=>d.close();return d;}
function gauge(label,val,max=1000){const n=Math.max(0,Number(val)||0),p=Math.max(2,Math.min(100,(n/max)*100));return `<div class="kcx-gauge"><div class="kcx-dial" style="--p:${p}"><div style="text-align:center"><b>${Math.round(n)} ms</b><small>${esc(label)}</small></div></div></div>`;}
async function api(action){flash('sup');const t=performance.now();const {data,error}=await sb.functions.invoke('kc-communication-console',{body:{action}});const total=performance.now()-t;if(error)throw error;return {data,total};}
async function localHealth(){const t=performance.now();await new Promise((ok,bad)=>{const r=indexedDB.open('kc-communication-public',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('health'))r.result.createObjectStore('health')};r.onsuccess=()=>{const db=r.result;try{const tx=db.transaction('health','readwrite');tx.objectStore('health').put(Date.now(),'kcx-ping');tx.oncomplete=()=>{db.close();ok()};tx.onerror=()=>bad(tx.error)}catch(e){db.close();bad(e)}};r.onerror=()=>bad(r.error)});flash('idx');return performance.now()-t;}
async function pushHealth(){flash('push');const t=performance.now();const {data,error}=await sb.functions.invoke('kc-communication-provider-health',{body:{}});if(error)throw error;return {data,total:performance.now()-t};}
async function openDiag(kind){const d=ensureModal(),b=d.querySelector('#kcxDiagBody');const names={idx:'IndexedDB / lokaler Speicher',sup:'Supabase / KC Communication',push:'Push / Provider'};b.innerHTML=`<h2>${names[kind]}</h2><div class="kcx-note">Messung noch nicht gestartet.</div><div style="margin-top:12px"><button class="kcx-action primary" id="kcxOne">Verbindung testen</button> <button class="kcx-action" id="kcxAll">Alle Wege testen</button></div>`;d.showModal();d.querySelector('#kcxOne').onclick=()=>runDiag(kind,b);d.querySelector('#kcxAll').onclick=()=>runAllDiag(b);await runDiag(kind,b);}
async function runDiag(kind,b){b.querySelector('.kcx-note').textContent='Messung läuft …';try{let a=0,z=0,detail='';if(kind==='idx'){a=await localHealth();z=a;detail='Lokaler Schreib-/Lesezugriff auf IndexedDB.'}else if(kind==='sup'){const r=await api('health');a=r.data?.latencyMs||0;z=r.total;detail=r.data?.ok?'Supabase-Datenbank antwortet.':'Supabase-Test meldet Fehler.'}else{const r=await pushHealth();z=r.total;const p=(r.data?.providers||[]).find(x=>x.channel==='push');a=Math.max(1,z*.35);detail=p?.outboundReady?'Web Push / VAPID ist versandbereit.':'Push ist nicht vollständig versandbereit.'}state.last[kind]={a,z,at:new Date()};b.querySelector('.kcx-note').outerHTML=`<div class="kcx-statusbar"><span class="kcx-pill ok">Verbindung erreichbar</span><span class="kcx-small">Messung ${new Date().toLocaleTimeString('de-DE')}</span></div><div class="kcx-gauges">${gauge(kind==='sup'?'DB-Reaktion':kind==='idx'?'Lokaler Zugriff':'Provider-Reaktion',a)}${gauge('Gesamtlaufzeit',z)}</div><div class="kcx-note">${esc(detail)}</div>`}catch(e){b.querySelector('.kcx-note').outerHTML=`<div class="kcx-note kcx-error">Test fehlgeschlagen: ${esc(e.message||e)}</div>`}}
async function runAllDiag(b){b.innerHTML='<h2>Alle Kommunikationswege</h2><div class="kcx-note">IDX, Supabase und Push werden nacheinander real getestet …</div>';const rows=[];for(const k of ['idx','sup','push']){try{const t=performance.now();if(k==='idx')await localHealth();else if(k==='sup')await api('health');else await pushHealth();rows.push([k.toUpperCase(),'OK',Math.round(performance.now()-t)])}catch(e){rows.push([k.toUpperCase(),'FEHLER',0])}}b.innerHTML+=`<table class="kcx-table"><thead><tr><th>Weg</th><th>Status</th><th>Gesamt</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td><span class="kcx-dot ${r[1]==='OK'?'green':'red'}"></span>${r[1]}</td><td>${r[2]} ms</td></tr>`).join('')}</tbody></table><div style="margin-top:12px"><button class="kcx-action" onclick="document.getElementById('kcxDiag').close()">Schließen</button></div>`;}
function programColor(p,c){if(p.status==='disabled'||p.status==='error')return ['red','Fehler / deaktiviert'];if(c){if(c.status==='pending')return ['blue','wartet auf Freigabe'];if(c.status==='active'){const age=c.last_seen_at?Date.now()-new Date(c.last_seen_at).getTime():Infinity;if(age<5*60e3)return ['green','live verbunden'];if(age<30*60e3)return ['yellow','Kontakt verzögert'];return ['blue','freigegeben, derzeit kein Live-Heartbeat'];}}if(p.status==='active')return ['blue','aktiv, noch kein Live-Client'];return ['gray','geplant / noch nicht gekoppelt'];}
async function getOverview(force=false){if(state.overview&&!force)return state.overview;const r=await api('overview');if(!r.data?.ok)throw new Error(r.data?.error||'Übersicht nicht verfügbar');state.overview=r.data;return state.overview;}
async function renderPrograms(){const el=document.getElementById('content');if(!el)return;el.innerHTML='<section class="card"><h2>Programme & Verbindungen</h2><div class="kcx-note">Live-Daten werden geladen …</div></section>';try{const o=await getOverview(true);el.innerHTML=`<section class="card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><h2 style="margin-bottom:4px">Programme & Verbindungen</h2><div class="muted">Fachprogramme, Maschinen-Clients und erlaubte Kommunikationswege.</div></div><button class="kcx-action" id="kcxProgReload">Aktualisieren</button></div><div style="overflow:auto;margin-top:12px"><table class="kcx-table"><thead><tr><th>Status</th><th>Programm</th><th>Client / Gerät</th><th>Letzter Kontakt</th><th>Versandwege</th></tr></thead><tbody>${(o.programs||[]).map(p=>{const c=(o.clients||[]).find(x=>x.source_program===p.id),s=programColor(p,c);return `<tr><td><span class="kcx-dot ${s[0]}"></span><b>${esc(s[1])}</b></td><td><b>${esc(p.display_name)}</b><div class="kcx-small">${esc(p.id)}</div></td><td>${c?esc(c.device_name||'Maschinen-Client'):'–'}${c?`<div class="kcx-small">Serverstatus: ${esc(c.status)}</div>`:''}</td><td>${c?.last_seen_at?new Date(c.last_seen_at).toLocaleString('de-DE'):'noch kein Heartbeat'}</td><td>${(p.allowed_channels||[]).map(x=>`<span class="kcx-pill info">${esc(String(x).toUpperCase())}</span>`).join(' ')||'–'}</td></tr>`}).join('')}</tbody></table></div><div class="kcx-note"><b>LED-Regel:</b> Grün = live verbunden · Gelb = verzögert/Verkehr · Rot = Fehler · Blau = registriert/freigegeben, aber derzeit kein Live-Heartbeat · Grau = geplant.</div></section>`;document.getElementById('kcxProgReload').onclick=renderPrograms}catch(e){el.innerHTML=`<section class="card"><h2>Programme & Verbindungen</h2><div class="kcx-note kcx-error">${esc(e.message||e)}</div></section>`}}
function providerStatus(p,r){if(!p)return ['gray','nicht konfiguriert'];if(r?.cost_policy==='locked_until_approved')return ['blue','vorbereitet / Kostensperre'];if(p.enabled&&p.status==='ready')return ['green','bereit'];if(p.enabled&&p.status==='test_ready')return ['yellow','Testbetrieb'];if(p.status==='prepared')return ['blue','vorbereitet'];return [p.enabled?'yellow':'gray',p.enabled?'aktiv':'inaktiv'];}
async function renderProviders(){const el=document.getElementById('content');if(!el)return;el.innerHTML='<section class="card"><h2>Provider & Versandwege</h2><div class="kcx-note">Provider werden geladen …</div></section>';try{const o=await getOverview(true),by={};(o.routes||[]).forEach(r=>(by[r.channel]??=[]).push(r));const channels=['email','push','sms','whatsapp'];el.innerHTML=`<section class="card"><h2>Provider & Versandwege</h2><p class="muted">Mehrere Provider pro Kanal mit Priorität, automatischem Failover und Kostensperre. Geheime Schlüssel bleiben ausschließlich serverseitig.</p><div class="kcx-grid">${channels.map(ch=>`<div class="kcx-provider"><h3>${ch==='email'?'✉️ E-Mail':ch==='push'?'🔔 Push':ch==='sms'?'💬 SMS':'🟢 WhatsApp'}</h3>${(by[ch]||[]).map(r=>{const p=(o.providers||[]).find(x=>x.id===r.provider_id),s=providerStatus(p,r);return `<div class="kcx-route"><div><span class="kcx-dot ${s[0]}"></span><b>${esc(p?.display_name||r.provider_id)}</b><div class="kcx-small">${esc(r.role)} · Priorität ${r.priority} · ${r.auto_failover?'Auto-Failover':'kein Auto-Failover'}</div><div class="kcx-small">Kostenregel: ${esc(r.cost_policy)}</div></div><div><span class="kcx-pill ${s[0]==='green'?'ok':s[0]==='red'?'bad':s[0]==='yellow'?'warn':'info'}">${esc(s[1])}</span></div></div>`}).join('')||'<div class="kcx-small">Noch kein Provider hinterlegt.</div>'}</div>`).join('')}</div><div class="actions"><button class="kcx-action primary" id="kcxProviderTest">Provider prüfen</button><button class="kcx-action" id="kcxAllTest">Alle Wege testen</button></div><div id="kcxProviderOut" class="kcx-note">Noch kein Test gestartet.</div></section>`;document.getElementById('kcxProviderTest').onclick=async()=>{const out=document.getElementById('kcxProviderOut');out.textContent='Providerprüfung läuft …';try{const r=await pushHealth();const a=r.data?.providers||[];out.innerHTML=a.map(x=>`<div><span class="kcx-dot ${x.outboundReady?'green':x.costLocked?'blue':'yellow'}"></span><b>${esc(String(x.channel).toUpperCase())}</b> · ${x.provider?esc(x.provider):'noch kein Provider'} · ${x.outboundReady?'versandbereit':x.costLocked?'Kostensperre':'noch nicht produktionsbereit'}</div>`).join('')||'Keine Providerdaten.'}catch(e){out.className='kcx-note kcx-error';out.textContent='Provider-Test fehlgeschlagen: '+(e.message||e)}};document.getElementById('kcxAllTest').onclick=()=>openDiag('sup')}catch(e){el.innerHTML=`<section class="card"><h2>Provider & Versandwege</h2><div class="kcx-note kcx-error">${esc(e.message||e)}</div></section>`}}
function hookTabs(){document.querySelectorAll('.tab').forEach(btn=>{if(btn.dataset.kcxHook)return;btn.dataset.kcxHook='1';btn.addEventListener('click',()=>setTimeout(()=>{if(btn.dataset.tab==='programs')renderPrograms();if(btn.dataset.tab==='settings')renderProviders();},0));});}
function observe(){enhanceLEDs();hookTabs();const mo=new MutationObserver(()=>{enhanceLEDs();hookTabs()});mo.observe(document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
})();