(()=>{'use strict';
const RUNTIME='0.3.1';
const paint=()=>document.querySelectorAll('.appVersion').forEach(x=>x.textContent=RUNTIME);
paint();new MutationObserver(paint).observe(document.body,{childList:true,subtree:true});
const prev=window.fetch.bind(window);
window.fetch=async(...args)=>{const u=String(args[0]?.url||args[0]||'');const r=await prev(...args);if(!u.includes('releases/latest.json'))return r;try{const m=await r.clone().json(),cmp=(a,b)=>{const A=String(a).split('.').map(Number),B=String(b).split('.').map(Number);for(let i=0;i<3;i++){if((A[i]||0)!==(B[i]||0))return (A[i]||0)-(B[i]||0)}return 0};if(cmp(m.version,RUNTIME)<=0){m.version='0.2.1';m.notes='KC Communication '+RUNTIME+' ist als Laufzeit-Erweiterung aktiv.';return new Response(JSON.stringify(m),{status:r.status,headers:{'content-type':'application/json','cache-control':'no-store'}})}}catch{}return r};
function ensureOverlay(){let o=document.getElementById('kcUpdateProgress');if(o)return o;o=document.createElement('div');o.id='kcUpdateProgress';o.innerHTML='<div class="kc-up-card"><div class="kc-up-logo">👨‍🍳</div><h2>KC Communication wird aktualisiert</h2><div id="kcUpVersion" class="kc-up-sub">Update wird vorbereitet …</div><div class="kc-up-track"><div id="kcUpBar" class="kc-up-bar"></div></div><div class="kc-up-row"><strong id="kcUpPct">0 %</strong><span id="kcUpEta">ca. 10–15 Sekunden</span></div><div id="kcUpStep" class="kc-up-step">Vorbereitung</div><div class="kc-up-note">Bitte dieses Fenster während des Updates nicht schließen.</div></div>';
const s=document.createElement('style');s.textContent='#kcUpdateProgress{position:fixed;inset:0;z-index:2147483647;background:rgba(28,21,18,.72);display:grid;place-items:center;padding:22px;font-family:Segoe UI,Arial,sans-serif}.kc-up-card{width:min(620px,94vw);background:#fff;border-radius:22px;padding:28px 30px;box-shadow:0 22px 70px rgba(0,0,0,.28);color:#2b2928}.kc-up-logo{text-align:center;font-size:54px}.kc-up-card h2{text-align:center;color:#741521;margin:8px 0}.kc-up-sub{text-align:center;color:#6d6966;margin-bottom:22px}.kc-up-track{height:24px;background:#ece6df;border-radius:999px;overflow:hidden;border:1px solid #ddd3ca}.kc-up-bar{height:100%;width:0;background:linear-gradient(90deg,#741521,#a12d40);transition:width .35s ease}.kc-up-row{display:flex;justify-content:space-between;gap:14px;margin-top:10px;font-size:17px}.kc-up-step{margin-top:20px;padding:12px 14px;background:#f5f1ec;border-radius:11px;font-weight:700}.kc-up-note{margin-top:12px;color:#6d6966;font-size:13px;text-align:center}';document.head.appendChild(s);document.body.appendChild(o);return o}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function installWithProgress(){const o=ensureOverlay(),bar=document.getElementById('kcUpBar'),pct=document.getElementById('kcUpPct'),eta=document.getElementById('kcUpEta'),step=document.getElementById('kcUpStep'),ver=document.getElementById('kcUpVersion');o.style.display='grid';let manifest={version:'neu',releaseUrl:'./'};try{manifest=await prev('./releases/latest.json?t='+Date.now(),{cache:'no-store'}).then(r=>r.json())}catch{}ver.textContent='Version '+manifest.version+' wird installiert';const stages=[{p:12,t:'Update-Paket wird geprüft …',d:700},{p:28,t:'Zwischenspeicher wird vorbereitet …',d:800},{p:48,t:'Neue Programmdateien werden geladen …',d:900},{p:66,t:'Service Worker und Laufzeit werden aktualisiert …',d:850},{p:82,t:'Verbindungen und Programmstart werden geprüft …',d:900},{p:94,t:'Abschlussprüfung …',d:650},{p:100,t:'Update erfolgreich. KC Communication startet neu …',d:700}];const started=Date.now();for(const st of stages){if(st.p===28&&'caches'in window){try{for(const k of await caches.keys())await caches.delete(k)}catch{}}if(st.p===66&&'serviceWorker'in navigator){try{const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs)await r.update()}catch{}}if(st.p===82){try{await prev('./index.html?verify='+Date.now(),{cache:'no-store'})}catch{}}bar.style.width=st.p+'%';pct.textContent=st.p+' %';step.textContent=st.t;const elapsed=(Date.now()-started)/1000,remaining=st.p>0?Math.max(1,Math.round(elapsed*(100-st.p)/st.p)):12;eta.textContent=st.p>=100?'fertig':'noch ca. '+remaining+' Sek.';await wait(st.d)}const target=(manifest.releaseUrl||'./').split('#')[0];location.replace(target+(target.includes('?')?'&':'?')+'installed='+encodeURIComponent(manifest.version)+'&t='+Date.now())}
document.addEventListener('click',e=>{const t=e.target;if(!(t instanceof Element))return;const b=t.closest('#installBtn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const d=document.getElementById('updateDialog');try{d&&d.close()}catch{}installWithProgress()},true);
})();